Add some HiP-CT docs
lincbrain/linc-docs pull request #18
Opened 2024-09-17 12:35 UTC by dstansby

This adds some docs on the HiP-CT data, including registrations, as requested by @kabilar. cc @ucbpclw

2024-09-20 03:40 UTC, kabilar commented on docs/data/hipct.md
> +There are then one or more datsets at higher resolution.
```suggestion
There are then one or more datasets at higher resolution.
```

2024-09-20 03:40 UTC, kabilar commented on docs/data/hipct.md
> +For example, a scan number of `402` is the second 4um scan.
```suggestion
For example, a chunk number of `402` is the second 4um scan.
```

2024-09-20 03:41 UTC, kabilar commented on docs/data/hipct.md
> +The highest lowest resolution dataset (equivalently, highest chunk number) is the overview dataset that contains an image of the whole sample.
```suggestion
The lowest resolution dataset (equivalently, highest chunk number) is the overview dataset that contains an image of the whole sample.
```

2024-09-20 03:41 UTC, kabilar commented on docs/test.md
Please remove this file.

2024-09-20 03:43 UTC, kabilar commented on docs/data/hipct.md
> +## Data information
```suggestion
## Data acquisition and naming
```

2024-09-20 03:51 UTC, kabilar commented on docs/data/hipct.md
> +The chunk number is set to `yyxx`, where yy is the resolution of the scan in micrometers, and xx is a scan number that is unique between datasets.
Perhaps we should use the [acq](https://bids-specification.readthedocs.io/en/stable/appendices/entities.html#acq) entity for the resolution.  The [chunk](https://bids-specification.readthedocs.io/en/stable/appendices/entities.html#chunk) entity could be used for different fields of view in the same sample.  If the same field of view is acquired multiple times then perhaps the [ses](https://bids-specification.readthedocs.io/en/stable/appendices/entities.html#ses) entity should be used.

2024-09-20 04:03 UTC, kabilar requested changes
Thank you @dstansby.  This is great.  I have a few suggestions above.

2024-09-30 10:58 UTC, dstansby commented on docs/data/hipct.md
> +The chunk number is set to `yyxx`, where yy is the resolution of the scan in micrometers, and xx is a scan number that is unique between datasets.
That sounds good - we could do `acq-overview` and `acq-zoom` for the low/high resolution scans. I don't think we have the same field of view multiple times, and if we do it won't be exactly the same scan/field of view so I don't think we need to use `ses`.

I'll take a look into renaming our datasets to use `acq`.

2024-10-01 14:55 UTC, kabilar commented on docs/data/hipct.md
> +The chunk number is set to `yyxx`, where yy is the resolution of the scan in micrometers, and xx is a scan number that is unique between datasets.
Thanks @dstansby.  Sounds great.

So for example the file `sub-I58_sample-blockIC2_chunk-201_PC.ome.zarr` would be renamed to `sub-I58_sample-blockIC2_acq-zoom_chunk-01_PC.ome.zarr` and `sub-I58_sample-blockIC2_chunk-401_PC.ome.zarr` would be renamed to `sub-I58_sample-blockIC2_acq-zoom_chunk-02_PC.ome.zarr`?

Since you are renaming files should we change the modality suffix?  If I am not mistaken, I believe that `PC` is now going to be `XPC`.

2024-10-14 16:05 UTC, dstansby commented on docs/data/hipct.md
> +The chunk number is set to `yyxx`, where yy is the resolution of the scan in micrometers, and xx is a scan number that is unique between datasets.
I think the new datasets would be called:

`sub-I58_sample-blockIC2_acq-zoom_chunk-01_PC.ome.zarr`
`sub-I58_sample-blockIC2_acq-overview_PC.ome.zarr`

For the overviews, we only have one per sample, so I think we don't want to use `chunk` for these datasets? If we end up more than one overview per sample (e.g., taken at different times or with different resolutions) we could then make the `acq` label more specific for each dataset (e.g., `acq-overview2025` if we do another one next year)

2025-01-20 17:00 UTC, dstansby commented on docs/data/hipct.md
> +The chunk number is set to `yyxx`, where yy is the resolution of the scan in micrometers, and xx is a scan number that is unique between datasets.
Given the PR documents the current state of affairs re. naming, it would be helpful from our end to merge this as is, and then raise a new issue for renaming of our datasets.

2025-02-05 23:36 UTC, kabilar commented on docs/data/hipct.md
> +The chunk number is set to `yyxx`, where yy is the resolution of the scan in micrometers, and xx is a scan number that is unique between datasets.
Thanks David.  That sounds good.  Filed https://github.com/lincbrain/linc-cloud/issues/10

2025-02-05 23:38 UTC, kabilar approved these changes

2025-02-05 23:38 UTC, merged