Add document for how to export annotations from webknossos
lincbrain/linc-docs pull request #28
Opened 2024-11-01 15:56 UTC by jingjingwu1225

2024-11-05 19:48 UTC, kabilar commented on docs/webknossos-export-annotation.md
Please update the [navigation](https://github.com/lincbrain/linc-docs/blob/d6e82b4293ce9472f85d673727911e7d25ead260/mkdocs.yml#L21-L32) with a link to this file.

2024-11-05 19:49 UTC, kabilar commented on docs/webknossos-export-annotation.md
> +	![](img/download2.png)
```suggestion
    ![](img/download2.png)
```

2024-11-05 20:18 UTC, jingjingwu1225 commented on docs/webknossos-export-annotation.md
Will do, Thanks!

2025-04-17 19:54 UTC, kabilar commented on docs/webknossos-export-annotation.md
> +6. Run Script webknossos_annotation.py to save into ome.zarr format following czyx direction.
```suggestion
6. Run the [webknossos_annotation.py](https://github.com/lincbrain/linc-convert/blob/main/linc_convert/modalities/wk/webknossos_annotation.py) script to save into the OME-Zarr format following the `czyx` direction. 
```

2025-04-17 19:55 UTC, kabilar commented on docs/webknossos-export-annotation.md
> +2. Click on Download on dropdown menu
```suggestion
2. Click `Download` in the dropdown `Menu`.
```

2025-04-17 19:55 UTC, kabilar commented on docs/webknossos-export-annotation.md
> +
```suggestion
1. Go to the `Annotations` tab and click `Open` for a desired annotation.
```

2025-04-17 19:56 UTC, kabilar commented on docs/webknossos-export-annotation.md
> +    ![](img/download.png)
```suggestion
    ![](img/webknossos_download.png)
```

2025-04-17 19:56 UTC, kabilar commented on docs/webknossos-export-annotation.md
> +    ![](img/download2.png)
```suggestion
    ![](img/webknossos_download_options.png)
```

2025-04-17 19:57 UTC, kabilar commented on docs/webknossos-export-annotation.md
> +4. Unzip downloaded annotation file
```suggestion
4. Unzip the downloaded annotation file.
```

2025-04-17 19:57 UTC, kabilar commented on docs/img/download.png
Please rename to `webknossos_download.png`.

2025-04-17 19:58 UTC, kabilar commented on docs/img/download2.png
Please rename to `webknossos_download_options.png`.

2025-04-17 19:58 UTC, kabilar commented on docs/webknossos-export-annotation.md
> +    ![](img/data_volume.png)
```suggestion
    ![](img/webknossos_data_volume.png)
```

2025-04-17 19:58 UTC, kabilar commented on docs/img/data_volume.png
Please rename to `webknossos_data_volume.png`.

2025-04-17 20:00 UTC, kabilar commented on docs/webknossos-export-annotation.md
> +3. Select "Include volume annotations as WKW" on pop out box and click on Download
```suggestion
3. Select "Include volume annotations as WKW" and click on `Download`.
```

2025-04-17 20:03 UTC, kabilar commented on docs/webknossos-export-annotation.md
> +5. Unzip data_Volume.zip under annotation folder
```suggestion
5. Unzip the `data_Volume.zip` file which is located in the annotation folder. 
```

2025-04-17 20:12 UTC, kabilar requested changes
Hi @jingjingwu1225, great work here on outlining this procedure.  I have some minor suggestions, but overall looks great.  Thanks.

2025-05-05 16:31 UTC, kabilar commented
Hi @jingjingwu1225, when you have a chance, could you please review my suggestions?  Thanks.

2025-05-09 14:23 UTC, merged